### ISSUE TITLE
Exception: Could not open file!

### ISSUE THREAD

**Issue by JuKu** [libgdx/gdx-video#42]
Hi,

I have tried to play an MP4 video, but there i get this exception:
```
java.lang.Exception: Could not open file!
	at com.badlogic.gdx.video.VideoDecoder.loadStream(Native Method)
	at com.badlogic.gdx.video.VideoPlayerDesktop.play(VideoPlayerDesktop.java:140)
	at com.pentaquin.gameclient.gamestate.IntroScene.initialize(IntroScene.java:69)
	at com.pentaquin.gameclient.Game.initialize(Game.java:48)
	at com.pentaquin.engine.adapter.GameAdapter.create(GameAdapter.java:47)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.video.VideoPlayerDesktop.renderTexture(VideoPlayerDesktop.java:249)
	at com.badlogic.gdx.video.VideoPlayerDesktop.render(VideoPlayerDesktop.java:228)
	at com.pentaquin.gameclient.gamestate.IntroScene.draw(IntroScene.java:238)
	at com.pentaquin.engine.component.scene.SceneComponent.draw(SceneComponent.java:45)
	at com.pentaquin.engine.adapter.GameAdapter.beforeDraw(GameAdapter.java:166)
	at com.pentaquin.engine.adapter.GameAdapter.render(GameAdapter.java:58)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
[VideoPlayer::loadFile] Error opening file: Invalid data found when processing input
```

@Robbiedobbie Which file formats are supported?

**Comment by JuKu** [comment]
How i play the video:

```java
//on initialization
VideoPlayer videoPlayer = VideoPlayerCreator.createVideoPlayer(viewport);
try {
    this.videoPlayer.play(Gdx.files.absolute("./data/video/intro_sequence.mp4"));
} catch (FileNotFoundException e) {
    e.printStackTrace();
}

//...

//in gameloop
videoPlayer.render();
```

**Comment by Robbiedobbie** [comment]
It might be a bug that went unnoticed. Can you try placing the video in your root folder, and see if can find the file?

**Comment by SimonIT** [comment]
Look at #68 for some current building hints
