### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by anbu93** [libgdx/gdx-video#44]
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: com.badlogic.gdx.video.FfMpeg.register()V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.UnsatisfiedLinkError: com.badlogic.gdx.video.FfMpeg.register()V
	at com.badlogic.gdx.video.FfMpeg.register(Native Method)
	at com.badlogic.gdx.video.FfMpeg.loadLibraries(FfMpeg.java:78)
	at com.badlogic.gdx.video.VideoPlayerDesktop.play(VideoPlayerDesktop.java:130)
```
OS: Ubuntu 16.04 LTS amd64 (need cross-platform solution)

Can anybody help?

PS: Issue#2 already tried.

**Comment by anbu93** [comment]
I'am sorry. Take the JAR-files, and it all worked. 
I think it's better to warn people that the repositories are not correct working:
"es.e-ucm.com.badlogicgames.gdx:gdx-video-desktop:0.0.1" 
Built in Gradle not work. I use 
with gradle compile files('libs/gdx-video-desktop.jar') for all projects.
