### ISSUE TITLE
Error on 1920x1080 videos in mp4, Could not find codec parameters for stream 0

### ISSUE THREAD

**Issue by roiniti** [libgdx/gdx-video#69]
I think this error only happens on mp4 videos 1080p or better quality, i don't know if anyone knows how to solve the problem but this is the error that i get:
`AL lib: (EE) alc_cleanup: 1 device not closed
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001ba4cdce960] stream 0, offset 0x30: partial file
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001ba4cdce960] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), 1920x1080, 295 kb/s): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Assertion desc failed at /gdx-video/gdx-video-desktop/FFmpeg/libswscale/swscale_internal.h:646
`

also i get this error on other mp4 video
`java.lang.Exception: Could not find stream info!
	at com.badlogic.gdx.video.VideoDecoder.loadStream(Native Method)
	at com.badlogic.gdx.video.CommonVideoPlayerDesktop.play(CommonVideoPlayerDesktop.java:89)
	at com.roiniti.jams.testP.GdxVideoTest.updateButtons(GdxVideoTest.java:83)
	at com.roiniti.jams.testP.GdxVideoTest.render(GdxVideoTest.java:73)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.roiniti.jams.JAMS.render(JAMS.java:175)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:403)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.roiniti.jams.desktop.AplicationThread$2.<init>(AplicationThread.java:47)
	at com.roiniti.jams.desktop.AplicationThread.run(AplicationThread.java:47)`

any ideas?

**Comment by SimonIT** [comment]
That's probably the location where the error happens:
https://github.com/libgdx/gdx-video/blob/74b978fdf4b4b4ebd09c3238bda5fe7e96432ecc/gdx-video-desktop/jni/VideoDecoder.cpp#L153-L156

**Comment by roiniti** [comment]
For the stream info i think its some decoder missing problem, I examinated the file and its audio its TWOS, I think its a format but i don't know exactly normally the audio its in mp4a format.
For the other error do you know what's happening?
