### ISSUE TITLE
NPE when playing ogg video without audio

### ISSUE THREAD

**Issue by mnn** [libgdx/gdx-video#9]
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.video.RawMusic.read(RawMusic.java:46)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.fill(OpenALMusic.java:240)
	at com.badlogic.gdx.backends.lwjgl.audio.OpenALMusic.play(OpenALMusic.java:85)
	at com.badlogic.gdx.video.VideoPlayerDesktop.render(VideoPlayerDesktop.java:205)
	at ...

[VideoPlayer::loadFile] Could not find audio stream!
```

**Comment by Robbiedobbie** [comment]
Thank you for reporting! Unfortunately, I'm really busy at the moment. I'll try to find some time as soon as possible though.

**Comment by mnn** [comment]
No need to rush it, I don't think many users will be playing video without sound ;). And also the workaround is pretty simple - adding silent audio track.

**Comment by Robbiedobbie** [comment]
I pushed a possible fix for this issue. Could you try out the code in PR #10? If it indeed fixes the bug, it will be merged to develop.

**Comment by mnn** [comment]
Yes, it does fix the bug. Thank you :). Here's the [sample file](https://mega.nz/#!FEhQRI4Z!n32WmgvLKxgIRaWQ-pkluTTJJL48DupqOIo5_-LaKkI) I was using.

**Comment by Robbiedobbie** [comment]
Great to hear it is working now!
